auth:
  handler: auth.handler
  environment:
    WEBSOCKETS_GITHUB_OAUTH_CLIENT_ID: ${env:WEBSOCKETS_GITHUB_OAUTH_CLIENT_ID}
    WEBSOCKETS_GITHUB_OAUTH_CLIENT_SECRET: ${env:WEBSOCKETS_GITHUB_OAUTH_CLIENT_SECRET}
  # cors:
  #   origin: ${self:custom.corsOrigin}

connect:
  events:
    - websocket:
        route: $connect
        authorizer:
          name: ${self:service}-auth #TODO: fix loadFunctions.js to handle this...
  handler: connect.handler
  environment:
    WEBSOCKETS_GITHUB_OAUTH_CLIENT_ID: ${env:WEBSOCKETS_GITHUB_OAUTH_CLIENT_ID}
    WEBSOCKETS_GITHUB_OAUTH_CLIENT_SECRET: ${env:WEBSOCKETS_GITHUB_OAUTH_CLIENT_SECRET}

default:
  events:
    - websocket:
        route: $default
  handler: default.handler

disconnect:
  events:
    - websocket:
        route: $disconnect
  handler: disconnect.handler

StartSendMessageNotification:
  handler: startSendMessageNotification.handler
  events:
    - sns:
        arn: arn:aws:sns:us-east-1:146665891952:AuthProcessedTopic #TODO: Deal with arn

GetConnection:
  handler: getConnection.handler

SendMessage:
  handler: sendMessage.handler

# broadcast:
#   events:
#     - websocket:
#         route: broadcast
#   handler: broadcast.handler
