KyleFinleyNet-${self:service}-SendMessage:
  definition:
    Comment: Send SNS message to client via APIGateway hosted WebSocket
    StartAt: GetConnection
    States:
      GetConnectionInvocation:
        Type: Task
        Resource:
          Fn::GetAtt: [GetConnection, Arn]
        Next: HasConnectionId
      HasConnectionId:
        Type: Choice
        Choices:
          - Variable: $.connectionId
            StringEquals: ""
            Next: Fail
        Default: SendMessage
      SendMessageInvocation:
        Type: Task
        Resource:
          Fn::GetAtt: [SendMessage, Arn]
        End: true
      Fail:
          Type: Fail
          End: true
