KyleFinleyNet-${self:service}-SendMessage:
  definition:
    Comment: Send SNS message to client via APIGateway hosted WebSocket
    StartAt: GetConnection
    States:
      GetConnection:
        Type: Task
        Resource:
          Fn::GetAtt: [GetConnection, Arn]
        Next: IsConnected
      IsConnected:
        Type: Choice
        Choices:
          - Variable: $.connectionId
            StringEquals: ""
            Next: Fail
        Default: SendMessage
      SendMessage:
        Type: Task
        Resource:
          Fn::GetAtt: [SendMessage, Arn]
        End: true
      Done:
          Type: Pass
          End: true
