apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
data:  
  rabbitmq-password: {{ .Values.rabbitmq.auth.password | b64enc | quote }}
  rabbitmq-erlang-cookie: {{ .Values.rabbitmq.auth.erlangCookie | b64enc | quote }}